# Generated by Django 5.2.6 on 2025-09-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_menuitem_product_delete_breakfastmenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
